import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="">
          {/* Logo / image on the left */}
          <Link
            href="/quizzes"
            className="w-full bg-blue-300 h-16 flex items-center px-6 shadow-md"
          >
            <Image
              src="vercel.svg"
              alt="Logo"
              className="h-10 w-10 object-contain mr-4"
              width={180}
              height={38}
            />
            <h1 className="text-white text-xl font-semibold">Quiz App</h1>
          </Link>
        </header>

        {children}
      </body>
    </html>
  );
}
